package com.mgr.pickMeCar.db.model.C;
// Generated 2016-03-07 13:22:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Token generated by hbm2java
 */
public class Token implements java.io.Serializable {

	private Integer id;
	private String token;
	private Date created;
	private Date expires;

	public Token() {
	}

	public Token(String token, Date created, Date expires) {
		this.token = token;
		this.created = created;
		this.expires = expires;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getExpires() {
		return this.expires;
	}

	public void setExpires(Date expires) {
		this.expires = expires;
	}

}
