package com.mgr.pickMeCar.db.model.C;
// Generated 2016-03-07 13:22:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private City city;
	private String name;
	private String email;
	private String password;
	private Set userGroups = new HashSet(0);
	private Set marks = new HashSet(0);
	private Set userTracks = new HashSet(0);
	private Set userCars = new HashSet(0);

	public User() {
	}

	public User(String password) {
		this.password = password;
	}

	public User(City city, String name, String email, String password, Set userGroups, Set marks, Set userTracks,
			Set userCars) {
		this.city = city;
		this.name = name;
		this.email = email;
		this.password = password;
		this.userGroups = userGroups;
		this.marks = marks;
		this.userTracks = userTracks;
		this.userCars = userCars;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set userGroups) {
		this.userGroups = userGroups;
	}

	public Set getMarks() {
		return this.marks;
	}

	public void setMarks(Set marks) {
		this.marks = marks;
	}

	public Set getUserTracks() {
		return this.userTracks;
	}

	public void setUserTracks(Set userTracks) {
		this.userTracks = userTracks;
	}

	public Set getUserCars() {
		return this.userCars;
	}

	public void setUserCars(Set userCars) {
		this.userCars = userCars;
	}

}
