package com.mgr.pickMeCar.db.model.C;
// Generated 2016-03-07 13:22:21 by Hibernate Tools 3.4.0.CR1

/**
 * UserTrack generated by hbm2java
 */
public class UserTrack implements java.io.Serializable {

	private int id;
	private Track track;
	private User user;

	public UserTrack() {
	}

	public UserTrack(int id, Track track, User user) {
		this.id = id;
		this.track = track;
		this.user = user;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Track getTrack() {
		return this.track;
	}

	public void setTrack(Track track) {
		this.track = track;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
