package com.mgr.pickMeCar.db.model;
// Generated 2016-03-14 15:22:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "drive_db")
public class City implements java.io.Serializable {

	private Integer id;
	private String name;
	private double latitude;
	private double longitude;
	private Set<User> users = new HashSet<User>(0);
	private Set<Through> throughs = new HashSet<Through>(0);

	public City() {
	}

	public City(String name, double latitude, double longitude) {
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public City(String name, double latitude, double longitude, Set<User> users, Set<Through> throughs) {
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.users = users;
		this.throughs = throughs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "latitude", nullable = false, precision = 22, scale = 0)
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 22, scale = 0)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "city")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "city")
	public Set<Through> getThroughs() {
		return this.throughs;
	}

	public void setThroughs(Set<Through> throughs) {
		this.throughs = throughs;
	}

}
