package com.mgr.pickMeCar.db.model;
// Generated 2016-03-14 13:58:12 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Through generated by hbm2java
 */
@Entity
@Table(name = "through", catalog = "drive_db")
public class Through implements java.io.Serializable {

	private Integer id;
	private City city;
	private Track track;
	private Double price;

	public Through() {
	}

	public Through(City city, Track track) {
		this.city = city;
		this.track = track;
	}

	public Through(City city, Track track, Double price) {
		this.city = city;
		this.track = track;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER
			)
	@JoinColumn(name = "idCity", nullable = false)
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTrack", nullable = false)
	public Track getTrack() {
		return this.track;
	}

	public void setTrack(Track track) {
		this.track = track;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
