package com.mgr.pickMeCar.db.model;
// Generated 2016-03-14 13:58:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "drive_db")
public class User implements java.io.Serializable {

	private Integer id;
	private City city;
	private String name;
	private String email;
	private String password;
	private Set userGroups = new HashSet(0);
	private Set marks = new HashSet(0);
	private Set userTracks = new HashSet(0);
	private Set userCars = new HashSet(0);

	public User() {
	}

	public User(String password) {
		this.password = password;
	}

	public User(City city, String name, String email, String password, Set userGroups, Set marks, Set userTracks,
			Set userCars) {
		this.city = city;
		this.name = name;
		this.email = email;
		this.password = password;
		this.userGroups = userGroups;
		this.marks = marks;
		this.userTracks = userTracks;
		this.userCars = userCars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "city")
	public City getCity() {
		return this.city;
	}
	
	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set userGroups) {
		this.userGroups = userGroups;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set getMarks() {
		return this.marks;
	}

	public void setMarks(Set marks) {
		this.marks = marks;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set getUserTracks() {
		return this.userTracks;
	}

	public void setUserTracks(Set userTracks) {
		this.userTracks = userTracks;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set getUserCars() {
		return this.userCars;
	}

	public void setUserCars(Set userCars) {
		this.userCars = userCars;
	}

}
