package com.mgr.pickMeCar.db.model;
// Generated 2016-03-14 15:22:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "drive_db")
public class User implements java.io.Serializable {

	private Integer id;
	private City city;
	private String name;
	private String email;
	private String password;
	private Set<UserGroup> userGroups = new HashSet<UserGroup>(0);
	private Set<Mark> marks = new HashSet<Mark>(0);
	private Set<UserTrack> userTracks = new HashSet<UserTrack>(0);
	private Set<UserCar> userCars = new HashSet<UserCar>(0);

	public User() {
	}

	public User(String password) {
		this.password = password;
	}

	public User(City city, String name, String email, String password, Set<UserGroup> userGroups, Set<Mark> marks,
			Set<UserTrack> userTracks, Set<UserCar> userCars) {
		this.city = city;
		this.name = name;
		this.email = email;
		this.password = password;
		this.userGroups = userGroups;
		this.marks = marks;
		this.userTracks = userTracks;
		this.userCars = userCars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "city")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set<UserGroup> getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set<UserGroup> userGroups) {
		this.userGroups = userGroups;
	}
 
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user" )
	public Set<Mark> getMarks() {
		return this.marks;
	}

	public void setMarks(Set<Mark> marks) {
		this.marks = marks;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set<UserTrack> getUserTracks() {
		return this.userTracks;
	}

	public void setUserTracks(Set<UserTrack> userTracks) {
		this.userTracks = userTracks;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set<UserCar> getUserCars() {
		return this.userCars;
	}

	public void setUserCars(Set<UserCar> userCars) {
		this.userCars = userCars;
	}

}
