package com.mgr.pickMeCar.db.model.REST;
// Generated 2016-03-07 13:22:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Car generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private Integer id;
	private String brand;
	private String model;
	private String space;
	private String description;
	private Set userCars = new HashSet(0);

	public Car() {
	}

	public Car(String brand, String model) {
		this.brand = brand;
		this.model = model;
	}

	public Car(String brand, String model, String space, String description, Set userCars) {
		this.brand = brand;
		this.model = model;
		this.space = space;
		this.description = description;
		this.userCars = userCars;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getSpace() {
		return this.space;
	}

	public void setSpace(String space) {
		this.space = space;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getUserCars() {
		return this.userCars;
	}

	public void setUserCars(Set userCars) {
		this.userCars = userCars;
	}

}
