package com.mgr.pickMeCar.db.model.REST;
// Generated 2016-03-07 13:22:21 by Hibernate Tools 3.4.0.CR1

/**
 * UserGroup generated by hbm2java
 */
public class UserGroup implements java.io.Serializable {

	private Integer id;
	private User user;
	private Groups groups;

	public UserGroup() {
	}

	public UserGroup(User user, Groups groups) {
		this.user = user;
		this.groups = groups;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

}
